version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=development
      - MYSQL_ADDR=mysql://sails:sails@database/sails_mysql
    ports:
      - 1337:1337
    command: npm run dev
    volumes:
      - ./:/app
  database:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=sails_mysql
      - MYSQL_USER=sails
      - MYSQL_PASSWORD=sails
      - MYSQL_ROOT_PASSWORD=sails